import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const base = [
  {
    id: "software-engineer",
    name: "Software Engineer",
    nameKn: "ಸಾಫ್ಟ್‌ವೇರ್ ಎಂಜಿನಿಯರ್",
    nameHi: "सॉफ्टवेयर इंजीनियर",
    domain: "tech",
    icon: "💻",
    avgSalary: "8-40 LPA",
    stream: "science",
    description:
      "Build apps, websites, and software systems",
    descriptionKn:
      "ಅಪ್ಲಿಕೇಶನ್‌ಗಳು, ವೆಬ್‌ಸೈಟ್‌ಗಳು ಮತ್ತು ಸಾಫ್ಟ್‌ವೇರ್ ವ್ಯವಸ್ಥೆಗಳನ್ನು ನಿರ್ಮಿಸಿ",
    entranceExams: ["JEE", "Karnataka CET", "COMEDK"],
    topCollegesKarnataka: [
      "IISc Bangalore",
      "NITK Surathkal",
      "RV College",
      "BMS College",
    ],
  },
  {
    id: "doctor",
    name: "Doctor (MBBS)",
    nameKn: "ವೈದ್ಯ",
    nameHi: "डॉक्टर",
    domain: "medicine",
    icon: "🩺",
    avgSalary: "10-50 LPA",
    stream: "science",
    description: "Diagnose and treat patients",
    descriptionKn: "ರೋಗಿಗಳನ್ನು ರೋಗನಿರ್ಣಯ ಮಾಡಿ ಮತ್ತು ಚಿಕಿತ್ಸೆ ನೀಡಿ",
    entranceExams: ["NEET"],
    topCollegesKarnataka: [
      "Manipal Medical College",
      "St Johns Medical",
      "Bangalore Medical College",
    ],
  },
  {
    id: "civil-engineer",
    name: "Civil Engineer",
    nameKn: "ಸಿವಿಲ್ ಎಂಜಿನಿಯರ್",
    nameHi: "सिविल इंजीनियर",
    domain: "engineering",
    icon: "🏗️",
    avgSalary: "5-20 LPA",
    stream: "science",
    description: "Design roads, bridges, buildings",
    descriptionKn: "",
    entranceExams: ["JEE", "Karnataka CET"],
    topCollegesKarnataka: ["NITK Surathkal", "BIT Bangalore", "UVCE"],
  },
  {
    id: "ias-officer",
    name: "IAS Officer",
    nameKn: "ಐಎಎಸ್ ಅಧಿಕಾರಿ",
    nameHi: "IAS अधिकारी",
    domain: "government",
    icon: "🏛️",
    avgSalary: "8-20 LPA + perks",
    stream: "any",
    description: "Serve the nation through civil services",
    descriptionKn: "",
    entranceExams: ["UPSC", "KPSC"],
    topCollegesKarnataka: ["Any degree college"],
  },
  {
    id: "ux-designer",
    name: "UX/UI Designer",
    nameKn: "ಯುಎಕ್ಸ್ ಡಿಸೈನರ್",
    nameHi: "UX डिज़ाइनर",
    domain: "creative",
    icon: "🎨",
    avgSalary: "5-25 LPA",
    stream: "any",
    description: "Design beautiful digital experiences",
    descriptionKn: "",
    entranceExams: ["NID", "NIFT"],
    topCollegesKarnataka: ["Srishti Manipal", "NIFT Bangalore"],
  },
  {
    id: "ca",
    name: "Chartered Accountant",
    nameKn: "ಚಾರ್ಟರ್ಡ್ ಅಕೌಂಟೆಂಟ್",
    nameHi: "चार्टर्ड अकाउंटेंट",
    domain: "commerce",
    icon: "📊",
    avgSalary: "7-30 LPA",
    stream: "commerce",
    description: "Manage finances, audits and taxation",
    descriptionKn: "",
    entranceExams: ["CA Foundation", "ICAI"],
    topCollegesKarnataka: ["Any Commerce College"],
  },
  {
    id: "lawyer",
    name: "Lawyer",
    nameKn: "ವಕೀಲ",
    nameHi: "वकील",
    domain: "law",
    icon: "⚖️",
    avgSalary: "5-30 LPA",
    stream: "any",
    description: "Represent clients and argue cases in court",
    descriptionKn: "",
    entranceExams: ["CLAT", "LSAT"],
    topCollegesKarnataka: ["Karnataka State Law University", "BMS Law College"],
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    nameKn: "ಡೇಟಾ ಸೈಂಟಿಸ್ಟ್",
    nameHi: "डेटा साइंटिस्ट",
    domain: "tech",
    icon: "📈",
    avgSalary: "10-50 LPA",
    stream: "science",
    description: "Analyse data to find patterns and insights",
    descriptionKn: "",
    entranceExams: ["JEE", "Karnataka CET"],
    topCollegesKarnataka: ["IISc", "IIIT Bangalore"],
  },
  {
    id: "architect",
    name: "Architect",
    nameKn: "ವಾಸ್ತುಶಿಲ್ಪಿ",
    nameHi: "वास्तुकार",
    domain: "creative",
    icon: "🏛️",
    avgSalary: "5-20 LPA",
    stream: "science",
    description: "Design buildings and spaces",
    descriptionKn: "",
    entranceExams: ["NATA", "JEE"],
    topCollegesKarnataka: ["BMS College", "RV Architecture"],
  },
  {
    id: "teacher",
    name: "Teacher / Professor",
    nameKn: "ಶಿಕ್ಷಕ",
    nameHi: "शिक्षक",
    domain: "education",
    icon: "📚",
    avgSalary: "3-15 LPA",
    stream: "any",
    description: "Shape the next generation through education",
    descriptionKn: "",
    entranceExams: ["TET", "CTET", "NET"],
    topCollegesKarnataka: ["Bangalore University", "Mysore University"],
  },
  {
    id: "pilot",
    name: "Pilot",
    nameKn: "ಪೈಲಟ್",
    nameHi: "पायलट",
    domain: "aviation",
    icon: "✈️",
    avgSalary: "15-60 LPA",
    stream: "science",
    description: "Fly commercial or private aircraft",
    descriptionKn: "",
    entranceExams: ["DGCA CPL", "NDA"],
    topCollegesKarnataka: ["Jakkur Flying Club", "Redbird Flight School"],
  },
  {
    id: "game-developer",
    name: "Game Developer",
    nameKn: "ಗೇಮ್ ಡೆವಲಪರ್",
    nameHi: "गेम डेवलपर",
    domain: "tech",
    icon: "🎮",
    avgSalary: "6-25 LPA",
    stream: "science",
    description: "Create video games and interactive experiences",
    descriptionKn: "",
    entranceExams: ["JEE", "MAHE"],
    topCollegesKarnataka: ["Manipal", "PES University"],
  },
  {
    id: "journalist",
    name: "Journalist",
    nameKn: "ಪತ್ರಕರ್ತ",
    nameHi: "पत्रकार",
    domain: "media",
    icon: "📰",
    avgSalary: "3-15 LPA",
    stream: "any",
    description: "Report news and tell important stories",
    descriptionKn: "",
    entranceExams: ["IIMC", "MJMC entrance"],
    topCollegesKarnataka: [
      "Manipal Institute of Communication",
      "Bangalore University",
    ],
  },
  {
    id: "psychologist",
    name: "Psychologist",
    nameKn: "ಮನೋವಿಜ್ಞಾನಿ",
    nameHi: "मनोवैज्ञानिक",
    domain: "healthcare",
    icon: "🧠",
    avgSalary: "4-20 LPA",
    stream: "science",
    description: "Help people with mental health and behaviour",
    descriptionKn: "",
    entranceExams: ["CUET", "State CET"],
    topCollegesKarnataka: ["Christ University", "Jyoti Nivas College"],
  },
  {
    id: "entrepreneur",
    name: "Entrepreneur",
    nameKn: "ಉದ್ಯಮಿ",
    nameHi: "उद्यमी",
    domain: "business",
    icon: "🚀",
    avgSalary: "Unlimited",
    stream: "any",
    description: "Start and build your own business",
    descriptionKn: "",
    entranceExams: ["None — just start!"],
    topCollegesKarnataka: [
      "NSRCEL IIMB",
      "T-Hub",
      "Bangalore startup ecosystem",
    ],
  },
];

const extras = [
  ["mechanical-engineer", "Mechanical Engineer", "ಮೆಕಾನಿಕಲ್ ಎಂಜಿನಿಯರ್", "मैकेनिकल इंजीनियर", "engineering", "⚙️", "6-22 LPA", "science", "Design machines, HVAC and manufacturing systems.", "ಯಂತ್ರಗಳು, ತಯಾರಿಕೆ ಮತ್ತು ವ್ಯವಸ್ಥೆಗಳನ್ನು ರೂಪಿಸಿ", ["JEE", "Karnataka CET"], ["NITK Surathkal", "RVCE", "MSRIT"]],
  ["electrical-engineer", "Electrical Engineer", "ವಿದ್ಯುತ್ ಎಂಜಿನಿಯರ್", "इलेक्ट्रिकल इंजीनियर", "engineering", "🔌", "5-18 LPA", "science", "Power systems, electronics and embedded design.", "ವಿದ್ಯುತ್ ವಿತರಣೆ ಮತ್ತು ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ವಿನ್ಯಾಸ", ["JEE", "Karnataka CET"], ["RVCE", "BMSCE", "UVCE"]],
  ["chemical-engineer", "Chemical Engineer", "ರಾಸಾಯನಿಕ ಎಂಜಿನಿಯರ್", "केमिकल इंजीनियर", "engineering", "🧪", "6-20 LPA", "science", "Process plants, materials and sustainable chemistry.", "ರಾಸಾಯನಿಕ ಪ್ರಕ್ರಿಯೆಗಳು ಮತ್ತು ಪ್ಲಾಂಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ", ["JEE", "Karnataka CET"], ["RVCE", "MIT Manipal"]],
  ["aerospace-engineer", "Aerospace Engineer", "ಏರೋಸ್ಪೇಸ್ ಎಂಜಿನಿಯರ್", "एयरोस्पेस इंजीनियर", "engineering", "🛰️", "8-30 LPA", "science", "Aircraft, satellites and propulsion systems.", "ವಿಮಾನಗಳು ಮತ್ತು ಉಪಗ್ರಹ ವ್ಯವಸ್ಥೆಗಳ ವಿನ್ಯಾಸ", ["JEE", "ISRO outreach"], ["IISc", "NITK"]],
  ["robotics-engineer", "Robotics Engineer", "ರೋಬೋಟಿಕ್ಸ್ ಎಂಜಿನಿಯರ್", "रोबोटिक्स इंजीनियर", "tech", "🤖", "7-28 LPA", "science", "Build robots, automation and control systems.", "ರೋಬೋಟ್‌ಗಳು ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ವ್ಯವಸ್ಥೆಗಳನ್ನು ತಯಾರಿಸಿ", ["JEE", "GATE"], ["IIIT Bangalore", "PES University"]],
  ["cybersecurity-analyst", "Cybersecurity Analyst", "ಸೈಬರ್ ಸುರಕ್ಷತಾ ವಿಶ್ಲೇಷಕ", "साइबर सुरक्षा विश्लेषक", "tech", "🛡️", "7-35 LPA", "science", "Protect systems, networks and data from attacks.", "ಡೇಟಾ ಮತ್ತು ನೆಟ್‌ವರ್ಕ್‌ಗಳನ್ನು ರಕ್ಷಿಸಿ", ["CEH", "CompTIA"], ["IIITB", "Christ University"]],
  ["network-engineer", "Network Engineer", "ನೆಟ್‌ವರ್ಕ್ ಎಂಜಿನಿಯರ್", "नेटवर्क इंजीनियर", "tech", "🌐", "5-22 LPA", "science", "Design and operate enterprise networks.", "ಕಂಪನಿ ನೆಟ್‌ವರ್ಕ್‌ಗಳನ್ನು ವಿನ್ಯಾಸಗೊಳಿಸಿ", ["CCNA", "JEE"], ["MSRIT", "DSCE"]],
  ["full-stack-developer", "Full Stack Developer", "ಫುಲ್ ಸ್ಟ್ಯಾಕ್ ಡೆವಲಪರ್", "फुल स्टैक डेवलपर", "tech", "🧩", "7-32 LPA", "science", "Ship end-to-end web products fast.", "ಮುಂಭಾಗ ಮತ್ತು ಹಿಂದಿನ ಭಾಗವನ್ನು ಒಟ್ಟಿಗೆ ನಿರ್ಮಿಸಿ", ["Bootcamps", "CET"], ["PES", "RVCE"]],
  ["mobile-developer", "Mobile App Developer", "ಮೊಬೈಲ್ ಅಪ್ ಡೆವಲಪರ್", "मोबाइल ऐप डेवलपर", "tech", "📱", "6-28 LPA", "science", "Create Android/iOS experiences users love.", "ಮೊಬೈಲ್ ಅಪ್ಲಿಕೇಶನ್‌ಗಳನ್ನು ರಚಿಸಿ", ["Kotlin/Swift skills"], ["PES", "DSU"]],
  ["nurse", "Nurse", "ನರ್ಸ್", "नर्स", "medicine", "💉", "3-12 LPA", "science", "Care for patients with empathy and skill.", "ರೋಗಿಗರ ಆರೈಕೆ ಮತ್ತು ನರ್ಸಿಂಗ್ ಕೌಶಲ್ಯ", ["NEET", "State nursing"], ["Manipal College of Nursing", "St. Johns"]],
  ["dentist", "Dentist", "ದಂತ ವೈದ್ಯ", "दंत चिकित्सक", "medicine", "🦷", "6-25 LPA", "science", "Oral health, surgery and community dentistry.", "ಬಾಯಿಯ ಆರೋಗ್ಯ ಮತ್ತು ದಂತ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ", ["NEET", "INI-CET"], ["MCODS Manipal", "RV Dental College"]],
  ["pharmacist", "Pharmacist", "ಫಾರ್ಮಾಸಿಸ್ಟ್", "फार्मासिस्ट", "medicine", "💊", "4-18 LPA", "science", "Medicines, quality control and patient counselling.", "ಔಷಧಿ ವಿತರಣೆ ಮತ್ತು ಸಲಹೆ", ["GPAT", "State CET"], ["Manipal College of Pharmacy", "CU"]],
  ["veterinary-doctor", "Veterinary Doctor", "ಪಶು ವೈದ್ಯ", "पशु चिकित्सक", "medicine", "🐾", "5-20 LPA", "science", "Animal healthcare and welfare.", "ಪ್ರಾಣಿಗಳ ಆರೋಗ್ಯ ರಕ್ಷಣೆ", ["KEAM", "State CET"], ["KVAFSU", "IVC Bengaluru"]],
  ["physiotherapist", "Physiotherapist", "ಫಿಸಿಯೋಥೆರಪಿಸ್ಟ್", "फिजियोथेरेपिस्ट", "healthcare", "🩹", "4-16 LPA", "science", "Rehabilitation, mobility and sports therapy.", "ಚಿಕಿತ್ಸೆ ಮತ್ತು ಚಲನಶಾಸ್ತ್ರ", ["BPT entrance"], ["Srinivas College", "MCHP Manipal"]],
  ["agricultural-scientist", "Agricultural Scientist", "ಕೃಷಿ ವಿಜ್ಞಾನಿ", "कृषि वैज्ञानिक", "science", "🌾", "4-15 LPA", "science", "Improve crops, soil and food security.", "ಬೆಳೆ ಮತ್ತು ಮಣ್ಣು ಸುಧಾರಣೆ", ["ICAR AIEEA"], ["UAS Bangalore", "UAS Dharwad"]],
  ["environmental-engineer", "Environmental Engineer", "ಪರಿಸರ ಎಂಜಿನಿಯರ್", "पर्यावरण इंजीनियर", "engineering", "🌿", "5-18 LPA", "science", "Water, waste and sustainability projects.", "ನೀರು, ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ ಮತ್ತು ಸಸ್ಟೈನೆಬಿಲಿಟಿ", ["GATE", "CET"], ["BMSCE", "UVCE"]],
  ["marine-biologist", "Marine Biologist", "ಸಮುದ್ರ ಜೀವಶಾಸ್ತ್ರಜ್ಞ", "समुद्री जीवविज्ञानी", "science", "🐠", "5-22 LPA", "science", "Study ocean life and ecosystems.", "ಸಮುದ್ರ ಜೀವಿಗಳ ಅಧ್ಯಯನ", ["IISc", "CUET"], ["NITK", "CMFRI collabs"]],
  ["economist", "Economist", "ಅರ್ಥಶಾಸ್ತ್ರಜ್ಞ", "अर्थशास्त्री", "commerce", "📉", "6-25 LPA", "commerce", "Markets, policy and development economics.", "ನೀತಿ ಮತ್ತು ಆರ್ಥಿಕ ವಿಶ್ಲೇಷಣೆ", ["CUET", "IIT HSEE"], ["IIMB policy roles", "UCE Bengaluru"]],
  ["chartered-financial-analyst", "Chartered Financial Analyst", "ಚಾರ್ಟರ್ಡ್ ಫೈನಾನ್ಷಿಯಲ್ ಅನಲಿಸ್ಟ್", "चार्टर्ड फाइनेंशियल एनालिस्ट", "commerce", "📈", "8-35 LPA", "commerce", "Investment research and portfolio strategy.", "ಹೂಡಿಕೆ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ವಿತ್ತೀಯ ಸಲಹೆ", ["CFA Program"], ["IIMB", "NMIMS Bengaluru"]],
  ["marketing-specialist", "Marketing Specialist", "ಮಾರ್ಕೆಟಿಂಗ್ ತಜ್ಞ", "मार्केटिंग विशेषज्ञ", "commerce", "📣", "5-22 LPA", "commerce", "Campaigns, growth and brand storytelling.", "ಬ್ರಾಂಡ್ ಮತ್ತು ಬೆಳವಣಿಗೆ ತಂತ್ರಗಳು", ["MBA entrances"], ["Christ University", "NMIMS"]],
  ["human-resources-manager", "Human Resources Manager", "ಮಾನವ ಸಂಪನ್ಮೂಲ ವ್ಯವಸ್ಥಾಪಕ", "मानव संसाधन प्रबंधक", "commerce", "🤝", "6-24 LPA", "commerce", "Hiring, culture and employee experience.", "ನೇಮಕಾತಿ ಮತ್ತು ಸಂಸ್ಕೃತಿ ನಿರ್ಮಾಣ", ["MBA", "PGDHRM"], ["XIME", "Symbiosis Bengaluru"]],
  ["operations-manager", "Operations Manager", "ಕಾರ್ಯಾಚರಣೆ ವ್ಯವಸ್ಥಾಪಕ", "ऑपरेशन्स मैनेजर", "commerce", "🏭", "7-28 LPA", "commerce", "Supply chain, quality and delivery excellence.", "ಸರಬರಾಜು ಸರಪಳಿ ಮತ್ತು качество", ["MBA", "Six Sigma"], ["IIMB ops", "Alliance University"]],
  ["graphic-designer", "Graphic Designer", "ಗ್ರಾಫಿಕ್ ಡಿಸೈನರ್", "ग्राफिक डिजाइनर", "creative", "✒️", "4-18 LPA", "arts", "Visual identity, illustration and branding.", "ಬ್ರಾಂಡಿಂಗ್ ಮತ್ತು ದೃಶ್ಯ ಕಲೆ", ["NID", "CEED"], ["Srishti", "NIFT Bangalore"]],
  ["interior-designer", "Interior Designer", "ಇಂಟೀರಿಯರ್ ಡಿಸೈನರ್", "इंटीरियर डिजाइनर", "creative", "🛋️", "4-16 LPA", "arts", "Spaces that feel human and functional.", "ಮನೆ ಮತ್ತು ಕಚೇರಿ ವಿನ್ಯಾಸ", ["NIFT", "State diplomas"], ["JD Institute", "Bangalore"]],
  ["fashion-designer", "Fashion Designer", "ಫ್ಯಾಷನ್ ಡಿಸೈನರ್", "फैशन डिजाइनर", "creative", "👗", "4-22 LPA", "arts", "Apparel, textiles and runway collections.", "ವಸ್ತ್ರ ವಿನ್ಯಾಸ ಮತ್ತು ಪೂರ್ವಾಗ್ರಹ", ["NIFT", "Pearl"], ["NIFT Bangalore", "Pearl Academy"]],
  ["filmmaker", "Filmmaker / Director", "ಚಲನಚಿತ್ರಕಾರ", "फिल्म निर्माता", "media", "🎬", "4-30 LPA", "arts", "Storytelling through cinema and OTT.", "ಸಿನಿಮಾ ಮತ್ತು ಡಾಕ್ಯುಮೆಂಟರಿಗಳು", ["FTII", "SRFTI"], ["LVPCMS Bengaluru", "FTII collabs"]],
  ["musician", "Musician / Composer", "ಸಂಗೀತಕಾರ", "संगीतकार", "creative", "🎵", "3-25 LPA", "arts", "Perform, compose and produce music.", "ಸಂಗೀತ ಪ್ರದರ್ಶನ ಮತ್ತು ರಚನೆ", ["AIEED", "Auditions"], ["Swathi Thirunal", "Private academies"]],
  ["sports-coach", "Sports Coach", "ಕ್ರೀಡಾ ತರಬೇತುದಾರ", "खेल कोच", "education", "🏅", "3-18 LPA", "any", "Train athletes and build fitness culture.", "ಕ್ರೀಡಾಪಟುಗಳಿಗೆ ತರಬೇತಿ ಮತ್ತು ತಂಡ ನಿರ್ಮಾಣ", ["NSIS diplomas"], ["SDAT Karnataka", "Sports Authority"]],
  ["police-officer", "Police Officer", "ಪೋಲಿಸ್ ಅಧಿಕಾರಿ", "पुलिस अधिकारी", "government", "👮", "4-18 LPA", "any", "Law enforcement and community safety.", "ಕಾನೂನು ಜಾರಿ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸುರಕ್ಷತೆ", ["KPSC", "SSC"], ["KPA Mysuru", "State selections"]],
  ["defence-officer", "Defence Officer", "ರಕ್ಷಣಾ ಅಧಿಕಾರಿ", "रक्षा अधिकारी", "government", "🎖️", "8-22 LPA + perks", "science", "Serve in Army/Navy/Air Force.", "ಸೇನೆಯಲ್ಲಿ ಸೇವೆ ಸಲ್ಲಿಸಿ", ["NDA", "CDS", "AFCAT"], ["National Defence Academy"]],
  ["social-worker", "Social Worker", "ಸಮಾಜ ಸೇವಕ", "सामाजिक कार्यकर्ता", "education", "🫶", "3-12 LPA", "arts", "Community welfare and grassroots programmes.", "ಸಮುದಾಯ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಸಹಾಯ", ["BSW/MSW entrances"], ["TISS remote", "Bangalore NGOs"]],
  ["chef", "Chef / Culinary Artist", "ಶೆಫ್", "शेफ / रसोइया", "business", "🍳", "4-25 LPA", "any", "Kitchen leadership and culinary creativity.", "ಅಡುಗೆ ಮತ್ತು ರೆಸ್ಟೋರೆಂಟ್ ನಿರ್ವಹಣೆ", ["IHM entrances"], ["IHM Bangalore", "WGSHA Manipal"]],
  ["hotel-manager", "Hotel Manager", "ಹೋಟೆಲ್ ವ್ಯವಸ್ಥಾಪಕ", "होटल प्रबंधक", "business", "🏨", "5-22 LPA", "commerce", "Guest experience and hospitality operations.", "ಆತಿಥ್ಯ ಮತ್ತು ಸೇವೆ ನಿರ್ವಹಣೆ", ["NCHMCT JEE"], ["WGSHA Manipal", "IHM Bangalore"]],
  ["astronomer", "Astronomer / Astrophysicist", "ಖಗೋಳಶಾಸ್ತ್ರಜ್ಞ", "खगोलशास्त्री", "science", "🔭", "6-25 LPA", "science", "Study stars, galaxies and instrumentation.", "ನಕ್ಷತ್ರಗಳು ಮತ್ತು ಉಪಕರಣಗಳ ಅಧ್ಯಯನ", ["IISc", "JEST"], ["IISc", "IIA Bengaluru"]],
  ["biotechnologist", "Biotechnologist", "ಜೈವ ತಂತ್ರಜ್ಞ", "जैव प्रौद्योगिकीविद्", "science", "🧬", "5-22 LPA", "science", "Genetics, vaccines and lab innovation.", "ಜೀನ್ ಎಡಿಟಿಂಗ್ ಮತ್ತು ಪ್ರಯೋಗಾಲಯ ಆವಿಷ್ಕಾರಗಳು", ["GATE-BT", "CUET"], ["IISc", "UAS Bangalore"]],
];

const filledBase = base.map((c) => ({
  ...c,
  descriptionKn:
    c.descriptionKn && c.descriptionKn.length > 0
      ? c.descriptionKn
      : `${c.description} (ಕನ್ನಡ ವಿವರಗಳಿಗೆ AI ಚಾಟ್ ಬಳಸಿ)`,
}));

const extraObjs = extras.map((row) => ({
  id: row[0],
  name: row[1],
  nameKn: row[2],
  nameHi: row[3],
  domain: row[4],
  icon: row[5],
  avgSalary: row[6],
  stream: row[7],
  description: row[8],
  descriptionKn: row[9],
  entranceExams: row[10],
  topCollegesKarnataka: row[11],
}));

const all = [...filledBase, ...extraObjs];

const output = `import type { CareerItem } from "@/types";

export const CAREERS: CareerItem[] = ${JSON.stringify(all, null, 2)};
`;

const target = path.join(__dirname, "..", "lib", "careers.ts");
fs.writeFileSync(target, output, "utf8");
console.log("Wrote", target, "careers:", all.length);
